queue_rules:
  - name: default
    conditions:
    - status-success=security-audit
    - status-success=check
    - status-success=lints
    - status-success=test (macos-latest, echo nothing-to-install)
    - status-success=test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
      libxcb-xfixes0-dev)
    - status-success=test (windows-latest, echo nothing-to-install)

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
    - status-success=security-audit
    - status-success=check
    - status-success=lints
    - status-success=test (macos-latest, echo nothing-to-install)
    - status-success=test (ubuntu-latest, sudo apt-get install -y libxcb-shape0-dev
      libxcb-xfixes0-dev)
    - status-success=test (windows-latest, echo nothing-to-install)
    - base=main
    - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
