[package]
name = "goodreads-quotes"
version = "0.1.0"
authors = ["Billie Thompson <billie@billiecodes.com>"]
edition = "2018"
description = "Pull random quotes from goodreads"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
scraper = "0.12.0"
rand = "0.7.3"
static-http-cache = "0.2.0"
directories-next = "1.0.1"
clap = "~2.33"
